install.packages("reshape")
install.packages("reshape2")
install.packages("data.table")
install.packages("dplyr")
library(dplyr)
library(reshape)
library(reshape2)
library(data.table)

features<-read.table("features.txt",header = FALSE) 
X_test<-read.table("test/X_test.txt",header = FALSE,col.names=c(as.character(features$V2))) 
X_train<-read.table("train/X_train.txt",header = FALSE,col.names=c(as.character(features$V2))) 
X<-rbind(X_test,X_train)
X2<-X[,c(grep(".mean..",names(X),ignore.case=FALSE,fixed=TRUE),grep(".std",names(X),ignore.case=FALSE,fixed=TRUE))]


activitylabeltest<-read.table("test/y_test.txt",header=FALSE,colClasses="factor")
activitylabeltrain<-read.table("train/y_train.txt",header=FALSE,colClasses="factor")
activitylabel<-rbind(activitylabeltest,activitylabeltrain)
subjecttest<-read.table("test/subject_test.txt",header=FALSE,colClasses="factor",col.names=c("subject"))
subjecttrain<-read.table("train/subject_train.txt",header=FALSE,colClasses="factor",col.names=c("subject"))
subject<-rbind(subjecttest,subjecttrain)
activitylabel<-factor(activitylabel$V1,labels=c("WALKING","WALKING_UPSTAIRS","WALKING_DOWNSTAIRS","SITTING","STANDING","LAYING"))
TIDY<-cbind(subject,activitylabel,X2)
TIDYmelt<-melt(TIDY,id=c("subject","activitylabel"),measure.vars=c(names(select(TIDY,-(subject:activitylabel)))))
TIDY2<-dcast(TIDYmelt, subject+activitylabel~variable,mean)
write.table(TIDY2,file="TIDY2.txt",row.name=FALSE)
